/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MentorApplicationRouteImport } from './routes/mentor-application'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as MeProfileRouteImport } from './routes/me.profile'
import { Route as SkillSkillIdRouteImport } from './routes/skill.$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorApplicationRoute = MentorApplicationRouteImport.update({
  id: '/mentor-application',
  path: '/mentor-application',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillSkillIdRoute = SkillSkillIdRouteImport.update({
  id: '/skill/$skillId',
  path: '/skill/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/forum': typeof ForumRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/mentor-application': typeof MentorApplicationRoute
  '/mentors': typeof MentorsRoute
  '/profile': typeof ProfileRoute
  '/sessions': typeof SessionsRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/me/profile': typeof MeProfileRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/forum': typeof ForumRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/mentor-application': typeof MentorApplicationRoute
  '/mentors': typeof MentorsRoute
  '/profile': typeof ProfileRoute
  '/sessions': typeof SessionsRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/me/profile': typeof MeProfileRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/forum': typeof ForumRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/mentor-application': typeof MentorApplicationRoute
  '/mentors': typeof MentorsRoute
  '/profile': typeof ProfileRoute
  '/sessions': typeof SessionsRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/me/profile': typeof MeProfileRoute
  '/skill/$skillId': typeof SkillSkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/forum'
    | '/instructor'
    | '/login'
    | '/mentor-application'
    | '/mentors'
    | '/profile'
    | '/sessions'
    | '/wallet'
    | '/watchlist'
    | '/me/profile'
    | '/skill/$skillId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/browse'
    | '/forum'
    | '/instructor'
    | '/login'
    | '/mentor-application'
    | '/mentors'
    | '/profile'
    | '/sessions'
    | '/wallet'
    | '/watchlist'
    | '/me/profile'
    | '/skill/$skillId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/forum'
    | '/instructor'
    | '/login'
    | '/mentor-application'
    | '/mentors'
    | '/profile'
    | '/sessions'
    | '/wallet'
    | '/watchlist'
    | '/me/profile'
    | '/skill/$skillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  ForumRoute: typeof ForumRoute
  InstructorRoute: typeof InstructorRoute
  LoginRoute: typeof LoginRoute
  MentorApplicationRoute: typeof MentorApplicationRoute
  MentorsRoute: typeof MentorsRoute
  ProfileRoute: typeof ProfileRoute
  SessionsRoute: typeof SessionsRoute
  WalletRoute: typeof WalletRoute
  WatchlistRoute: typeof WatchlistRoute
  MeProfileRoute: typeof MeProfileRoute
  SkillSkillIdRoute: typeof SkillSkillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-application': {
      id: '/mentor-application'
      path: '/mentor-application'
      fullPath: '/mentor-application'
      preLoaderRoute: typeof MentorApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$skillId': {
      id: '/skill/$skillId'
      path: '/skill/$skillId'
      fullPath: '/skill/$skillId'
      preLoaderRoute: typeof SkillSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  ForumRoute: ForumRoute,
  InstructorRoute: InstructorRoute,
  LoginRoute: LoginRoute,
  MentorApplicationRoute: MentorApplicationRoute,
  MentorsRoute: MentorsRoute,
  ProfileRoute: ProfileRoute,
  SessionsRoute: SessionsRoute,
  WalletRoute: WalletRoute,
  WatchlistRoute: WatchlistRoute,
  MeProfileRoute: MeProfileRoute,
  SkillSkillIdRoute: SkillSkillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
